function makeToggle(id, onChange) {
  const el = document.getElementById(id)
  el.addEventListener('click', () => {
    el.classList.toggle('active')
    onChange(el.classList.contains('active'))
  })
  return el
}

export function initControls({ onOpacity, onBorders, onLabels, onDragMode, onEquator, onCapitals, onSolarSystem, onSun, onCityLights, onAurora, onWeatherClick, onEarthquakes, onSatellites, onIss, onTectonic, onCountryInfo, onTimezones, onCurrents, onShips, onMeteors, onReset }) {
  const dragToggle          = makeToggle('drag-toggle',          onDragMode)
  const labelsToggle        = makeToggle('labels-toggle',        onLabels)
  const bordersToggle       = makeToggle('borders-toggle',       onBorders)
  const transparentToggle   = makeToggle('transparent-toggle',   onOpacity)
  const equatorToggle       = makeToggle('equator-toggle',       onEquator)
  const capitalsToggle      = makeToggle('capitals-toggle',      onCapitals)
  const solarToggle         = makeToggle('solar-toggle',         onSolarSystem)
  const sunToggle           = makeToggle('sun-toggle',           onSun)
  const cityLightsToggle    = makeToggle('citylights-toggle',    onCityLights)
  const auroraToggle        = makeToggle('aurora-toggle',        onAurora)
  const weatherToggle       = makeToggle('weather-toggle',       onWeatherClick)
  const earthquakesToggle   = makeToggle('earthquakes-toggle',   onEarthquakes)
  const satellitesToggle    = makeToggle('satellites-toggle',    onSatellites)
  const issToggle           = makeToggle('iss-toggle',           onIss)
  const tectonicToggle      = makeToggle('tectonic-toggle',      onTectonic)
  const countryInfoToggle   = makeToggle('countryinfo-toggle',   onCountryInfo)
  const timezonesToggle     = makeToggle('timezones-toggle',     onTimezones)
  const currentsToggle      = makeToggle('currents-toggle',      onCurrents)
  const shipsToggle         = makeToggle('ships-toggle',         onShips)
  const meteorsToggle       = makeToggle('meteors-toggle',       onMeteors)

  document.getElementById('compass')?.addEventListener('click', onReset)

  onDragMode(dragToggle.classList.contains('active'))
  onLabels(labelsToggle.classList.contains('active'))
  onBorders(bordersToggle.classList.contains('active'))
  onOpacity(transparentToggle.classList.contains('active'))
  onEquator(equatorToggle.classList.contains('active'))
  onCapitals(capitalsToggle.classList.contains('active'))
  onSolarSystem(solarToggle.classList.contains('active'))
  onSun(sunToggle.classList.contains('active'))
  onCityLights(cityLightsToggle.classList.contains('active'))
  onAurora(auroraToggle.classList.contains('active'))
  onWeatherClick(weatherToggle.classList.contains('active'))
  onEarthquakes(earthquakesToggle.classList.contains('active'))
  onSatellites(satellitesToggle.classList.contains('active'))
  onIss(issToggle.classList.contains('active'))
  onTectonic(tectonicToggle.classList.contains('active'))
  onCountryInfo(countryInfoToggle.classList.contains('active'))
  onTimezones(timezonesToggle.classList.contains('active'))
  onCurrents(currentsToggle.classList.contains('active'))
  onShips(shipsToggle.classList.contains('active'))
  onMeteors(meteorsToggle.classList.contains('active'))
}
